version: "3"
services:
    whatsapp-bot:
        container_name: whatsapp-bot
        read_only: true
        image: ghcr.io/emiliocalvet/whatsapp-bot:refactor
        restart: unless-stopped
        volumes:
            - session-data:/app/session
volumes:
    session-data:
